pull_request_title: 'feat(locales): updated translation from Crowdin'
pull_request_labels:
  - crowdin
preserve_hierarchy: true
files:
  - source: /organized/i18n/en/**/*
    translation: /organized/i18n/%two_letters_code%/**/%original_file_name%
  - source: /organized/docs/**/*
    translation: /organized/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /organized/blog/**/*
    ignore:
      - '*.yml'
    translation: /organized/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
