name: Scorecards

on:
  branch_protection_rule:
  schedule:
    - cron: '0 12 * * 4'
  push:
    branches: [main]

permissions: read-all

jobs:
  scorecards:
    name: Scorecards Analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Used to receive a badge. (Upcoming feature)
      id-token: write
      actions: read
      contents: read

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          persist-credentials: false

      - name: 'Run analysis'
        uses: ossf/scorecard-action@e38b1902ae4f44df626f11ba0734b14fb91f8f86
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: 'Upload to code-scanning'
        uses: github/codeql-action/upload-sarif@7df0ce34898d659f95c0c4a09eaa8d4e32ee64db
        with:
          sarif_file: results.sarif
